fixing strawberryperl nuget path, Run.pl doesn't work yet on my machine, maybe some of the directories or files moved and this script needs more adjustments
Runall.pl line 900:  Fatal Error: No such file or directory
Could not open fail list 'failures.lst'.
C:\dev\src\github.com\Microsoft\visualfsharp\tests\fsharpqa\..\..\tests\fsharpqa\testenv\bin\runall.pl terminated abnormally.
Can't use an undefined value as a symbol reference at C:\dev\src\github.com\Microsoft\visualfsharp\tests\fsharpqa\..\..\tests\fsharpqa\testenv\bin\runall.pl line 1002.
> System.Exception: exit code: 2
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
   at FSI_0019.runPerl(String[] arguments) in C:\dev\src\github.com\Microsoft\visualfsharp\tests\fsharpqa\run.fsharpqa.test.fsx:line 59
   at <StartupCode$FSI_0019>.$FSI_0019.main@() in C:\dev\src\github.com\Microsoft\visualfsharp\tests\fsharpqa\run.fsharpqa.test.fsx:line 62
Stopped due to error