Fix for codeplex issue 201:
Enabling warnings as errors for all projects causes ProjectSystem.Base to fail to build. In both master and fsharp 4.

 "C:\visualfsharp\vsintegration\fsharp-vsintegration-build.proj" (default target) (1) ->
 "C:\visualfsharp\vsintegration\src\Deployment.sln" (Build target) (2) ->
 "C:\visualfsharp\vsintegration\src\deployment\EnableOpenSource\EnableOpenSource.csproj" (default target) (3) ->
 "C:\visualfsharp\vsintegration\src\vs\FsPkgs\FSharp.Project\Common.Source.CSharp\Project\ProjectSystem.Base.csproj" (default
 target) (12) ->
 (CoreCompile target) ->
 DataObject.cs(431,37): error CS8073: The result of the expression is always 'true' since a value of type 'IntPtr' is never
 equal to 'null' of type 'IntPtr?' [C:\visualfsharp\vsintegration\src\vs\FsPkgs\FSharp.Project\Common.Source.CSharp\Project\
 ProjectSystem.Base.csproj]

Use IntPtr.Zero instead of null

 (changeset 1391801)